Первая версия интеграции алгоримтов
YaccConstructor/RedisGraph pull request #3
Opened 2019-10-11 15:51 UTC by simpletonDL

Добавил механизм регистрации алгоримтов, реализаию первого алгоритма на cpu, и ещё возможность нетерминалов быть строкой.

2019-10-11 18:13 UTC, gsvgit requested changes

2019-10-11 18:13 UTC, gsvgit commented on src/cfpq_algorithms/algo_restrator.c
> +#include "algo_restrator.h"
Is it really "algo_restraor", not "algo_registrator"?

2019-10-11 19:42 UTC, simpletonDL commented on src/cfpq_algorithms/algo_restrator.c
> +#include "algo_restrator.h"
Oh no, it`s mistake.

2019-10-12 19:15 UTC, gsvgit approved these changes

2019-10-12 19:15 UTC, merged